### ISSUE TITLE
Outer layer of hands and body not only head

### ISSUE THREAD

**Issue by BillCipher345** [tweska/BetaFix#3]
What the title says, it just doesnt show the outer layer on body except heads.

**Comment by tweska** [comment]
The hat layer only applies to the full body since 1.8. So this is simply not supported by the game.

**Comment by BillCipher345** [comment]
But this is a mod, it changes the game, y not add a support for that?

**Comment by tweska** [comment]
I am not interested in adding features that where not there during beta. Feel free to fork though.

**Comment by BillCipher345** [comment]
Kk, idk how to code in java tho, but if ill learn, ill fork it
